apiVersion: tuned.openshift.io/v1
kind: Tuned
metadata:
  name: intel-kpm-hotfixes
  namespace: openshift-cluster-node-tuning-operator
spec:
  profile:
  - data: |
      [main]
      summary=Configuration changes profile inherited from performance created tuned

      # https://access.redhat.com/solutions/5532341
      include=openshift-node-performance-intel-kpm
      [bootloader]
      cmdline_removeKernelArgs=-intel_pstate=disable
    name: openshift-intel-kpm-hotfixes
  recommend:
  - machineConfigLabels:
      machineconfiguration.openshift.io/role: "intel-kpm"
    # lower number == higer priority
    priority: 15
    profile: openshift-intel-kpm-hotfixes